// Auto-generated by @farming-labs/next — do not edit manually.

import docsConfig from "@/docs.config";
import { createDocsMCPAPI, resolveNextProjectRoot } from "@farming-labs/next/api";

const rootDir = resolveNextProjectRoot(import.meta.url);

export const { GET, POST, DELETE } = createDocsMCPAPI({
  rootDir,
  entry: docsConfig.entry,
  contentDir: docsConfig.contentDir,
  nav: docsConfig.nav,
  ordering: docsConfig.ordering,
  search: docsConfig.search,
  mcp: docsConfig.mcp,
});

export const revalidate = false;
