import { execFile } from "node:child_process";
import { userInfo } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";
import { describe, expect, it } from "vitest";
import mysql from "mysql2/promise";
import { Pool } from "pg";
import { createOrm } from "@farming-labs/orm";
import { createPrismaDriver } from "../src";
import {
  assertBelongsToAndManyToManyQueries,
  assertMutationQueries,
  assertOneToOneAndHasManyQueries,
  schema,
  type RuntimeOrm,
} from "./support/auth";
// Generated by `pnpm run prisma:prepare` before the test process starts.
// @ts-ignore generated test fixture
import { PrismaClient as SqlitePrismaClient } from "./fixtures/sqlite/generated/client/index.js";
// Generated by `pnpm run prisma:prepare` before the test process starts.
// @ts-ignore generated test fixture
import { PrismaClient as PostgresqlPrismaClient } from "./fixtures/postgresql/generated/client/index.js";
// Generated by `pnpm run prisma:prepare` before the test process starts.
// @ts-ignore generated test fixture
import { PrismaClient as MysqlPrismaClient } from "./fixtures/mysql/generated/client/index.js";

const execFileAsync = promisify(execFile);
const dirname = path.dirname(fileURLToPath(import.meta.url));
const packageRoot = path.resolve(dirname, "..");
const LOCAL_TIMEOUT_MS = 30_000;

const prismaTargets = ["sqlite", "postgresql", "mysql"] as const;

type PrismaTarget = (typeof prismaTargets)[number];

type RealGeneratedPrismaClient = {
  user: { deleteMany(): Promise<unknown> };
  profile: { deleteMany(): Promise<unknown> };
  session: { deleteMany(): Promise<unknown> };
  organization: { deleteMany(): Promise<unknown> };
  member: { deleteMany(): Promise<unknown> };
  $connect(): Promise<void>;
  $disconnect(): Promise<void>;
  $queryRawUnsafe<T = unknown>(query: string, ...values: unknown[]): Promise<T>;
};

type RealGeneratedPrismaClientCtor = new (...args: any[]) => RealGeneratedPrismaClient;

type RuntimeFactory = () => Promise<{
  orm: RuntimeOrm;
  prisma: RealGeneratedPrismaClient;
  close: () => Promise<void>;
}>;

const requestedTargetValues = (process.env.FARM_ORM_LOCAL_PRISMA_TARGETS ?? "")
  .split(",")
  .map((value) => value.trim())
  .filter(Boolean);
const invalidTargets = requestedTargetValues.filter(
  (value): value is string => !(prismaTargets as readonly string[]).includes(value),
);

if (invalidTargets.length) {
  throw new Error(
    `Invalid FARM_ORM_LOCAL_PRISMA_TARGETS values: ${invalidTargets.join(", ")}. Expected one of: ${prismaTargets.join(", ")}.`,
  );
}

const requestedTargets = new Set(requestedTargetValues as PrismaTarget[]);

function shouldRunTarget(target: PrismaTarget) {
  return requestedTargets.size === 0 || requestedTargets.has(target);
}

function createIsolatedName(prefix: string) {
  return `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`.replace(/-/g, "_");
}

function assignDatabase(connectionString: string, databaseName: string) {
  const url = new URL(connectionString);
  url.pathname = `/${databaseName}`;
  return url.toString();
}

function fixtureSchemaPath(target: PrismaTarget) {
  return path.join(dirname, "fixtures", target, "schema.prisma");
}

const generatedPrismaClients = {
  sqlite: SqlitePrismaClient,
  postgresql: PostgresqlPrismaClient,
  mysql: MysqlPrismaClient,
} satisfies Record<PrismaTarget, RealGeneratedPrismaClientCtor>;

function getGeneratedPrismaClient(target: PrismaTarget): RealGeneratedPrismaClientCtor {
  return generatedPrismaClients[target] as RealGeneratedPrismaClientCtor;
}

async function resetDatabase(prisma: RealGeneratedPrismaClient) {
  await prisma.member.deleteMany();
  await prisma.session.deleteMany();
  await prisma.profile.deleteMany();
  await prisma.organization.deleteMany();
  await prisma.user.deleteMany();
}

async function createPrismaOrm(target: PrismaTarget, url: string) {
  process.env.DATABASE_URL = url;
  const PrismaClient = getGeneratedPrismaClient(target);
  const prisma = new PrismaClient({
    datasources: {
      db: {
        url,
      },
    },
  });

  // This is a real generated PrismaClient instance, not the fake delegate test double.
  await prisma.$connect();
  await prisma.$queryRawUnsafe("SELECT 1");

  const orm = createOrm({
    schema,
    driver: createPrismaDriver({
      client: prisma as any,
    }),
  }) as RuntimeOrm;

  await resetDatabase(prisma);

  return {
    orm,
    prisma,
  };
}

async function pushSchema(target: Exclude<PrismaTarget, "sqlite">, databaseUrl: string) {
  await execFileAsync(
    "pnpm",
    ["exec", "prisma", "db", "push", "--schema", fixtureSchemaPath(target), "--skip-generate"],
    {
      cwd: packageRoot,
      env: {
        ...process.env,
        DATABASE_URL: databaseUrl,
      },
    },
  );
}

function formatLocalDbError(label: string, error: unknown, hint: string) {
  const message = error instanceof Error ? error.message : String(error);
  return new Error(
    `${label} local Prisma integration test could not connect. ${hint}\nOriginal error: ${message}`,
  );
}

async function resolvePostgresAdminUrl() {
  const candidates = [
    process.env.FARM_ORM_LOCAL_PG_ADMIN_URL,
    "postgres://postgres:postgres@127.0.0.1:5432/postgres",
    `postgres://${userInfo().username}@127.0.0.1:5432/postgres`,
  ].filter(Boolean) as string[];

  let lastError: unknown;
  for (const candidate of candidates) {
    const pool = new Pool({ connectionString: candidate });
    try {
      await pool.query("SELECT 1");
      await pool.end();
      return candidate;
    } catch (error) {
      lastError = error;
      await pool.end().catch(() => undefined);
    }
  }

  throw formatLocalDbError(
    "PostgreSQL",
    lastError,
    `Make sure a local PostgreSQL server is running and reachable via FARM_ORM_LOCAL_PG_ADMIN_URL (tried: ${candidates.join(", ")}).`,
  );
}

async function resolveMysqlAdminUrl() {
  const candidates = [
    process.env.FARM_ORM_LOCAL_MYSQL_ADMIN_URL,
    "mysql://root@127.0.0.1:3306",
    "mysql://root:root@127.0.0.1:3306",
  ].filter(Boolean) as string[];

  let lastError: unknown;
  for (const candidate of candidates) {
    const pool = mysql.createPool(candidate);
    try {
      await pool.query("SELECT 1");
      await pool.end();
      return candidate;
    } catch (error) {
      lastError = error;
      await pool.end().catch(() => undefined);
    }
  }

  throw formatLocalDbError(
    "MySQL",
    lastError,
    `Make sure a local MySQL server is running and reachable via FARM_ORM_LOCAL_MYSQL_ADMIN_URL (tried: ${candidates.join(", ")}).`,
  );
}

async function createLocalSqliteOrm() {
  const databasePath = path.join(dirname, "fixtures", "sqlite", "dev.db");
  const databaseUrl = `file:${databasePath}`;
  const { orm, prisma } = await createPrismaOrm("sqlite", databaseUrl);

  return {
    orm,
    prisma,
    close: async () => {
      await resetDatabase(prisma).catch(() => undefined);
      await prisma.$disconnect();
    },
  } satisfies Awaited<ReturnType<RuntimeFactory>>;
}

async function createLocalPostgresOrm() {
  const adminUrl = await resolvePostgresAdminUrl();
  const databaseName = createIsolatedName("farm_orm_prisma_pg");
  const adminPool = new Pool({ connectionString: adminUrl });

  try {
    await adminPool.query(`CREATE DATABASE "${databaseName}"`);
  } catch (error) {
    await adminPool.end();
    throw formatLocalDbError(
      "PostgreSQL",
      error,
      `Make sure a local PostgreSQL server is running and reachable via FARM_ORM_LOCAL_PG_ADMIN_URL (resolved admin URL: ${adminUrl}).`,
    );
  }

  await adminPool.end();

  const databaseUrl = assignDatabase(adminUrl, databaseName);

  try {
    await pushSchema("postgresql", databaseUrl);
  } catch (error) {
    const cleanupAdmin = new Pool({ connectionString: adminUrl });
    await cleanupAdmin.query(`DROP DATABASE IF EXISTS "${databaseName}"`);
    await cleanupAdmin.end();
    throw error;
  }

  const { orm, prisma } = await createPrismaOrm("postgresql", databaseUrl);

  return {
    orm,
    prisma,
    close: async () => {
      await prisma.$disconnect();
      const cleanupAdmin = new Pool({ connectionString: adminUrl });
      await cleanupAdmin.query(
        "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = $1 AND pid <> pg_backend_pid()",
        [databaseName],
      );
      await cleanupAdmin.query(`DROP DATABASE IF EXISTS "${databaseName}"`);
      await cleanupAdmin.end();
    },
  } satisfies Awaited<ReturnType<RuntimeFactory>>;
}

async function createLocalMysqlOrm() {
  const adminUrl = await resolveMysqlAdminUrl();
  const databaseName = createIsolatedName("farm_orm_prisma_mysql");
  const adminPool = mysql.createPool(adminUrl);

  try {
    await adminPool.query(`CREATE DATABASE \`${databaseName}\``);
  } catch (error) {
    await adminPool.end();
    throw formatLocalDbError(
      "MySQL",
      error,
      `Make sure a local MySQL server is running and reachable via FARM_ORM_LOCAL_MYSQL_ADMIN_URL (resolved admin URL: ${adminUrl}).`,
    );
  }

  await adminPool.end();

  const databaseUrl = assignDatabase(adminUrl, databaseName);

  try {
    await pushSchema("mysql", databaseUrl);
  } catch (error) {
    const cleanupAdmin = mysql.createPool(adminUrl);
    await cleanupAdmin.query(`DROP DATABASE IF EXISTS \`${databaseName}\``);
    await cleanupAdmin.end();
    throw error;
  }

  const { orm, prisma } = await createPrismaOrm("mysql", databaseUrl);

  return {
    orm,
    prisma,
    close: async () => {
      await prisma.$disconnect();
      const cleanupAdmin = mysql.createPool(adminUrl);
      await cleanupAdmin.query(`DROP DATABASE IF EXISTS \`${databaseName}\``);
      await cleanupAdmin.end();
    },
  } satisfies Awaited<ReturnType<RuntimeFactory>>;
}

for (const [target, factory] of [
  ["sqlite", createLocalSqliteOrm],
  ["postgresql", createLocalPostgresOrm],
  ["mysql", createLocalMysqlOrm],
] as const satisfies ReadonlyArray<readonly [PrismaTarget, RuntimeFactory]>) {
  describe.runIf(shouldRunTarget(target))(`${target} local Prisma integration`, () => {
    it(
      "creates and uses a real generated PrismaClient against a real local database",
      async () => {
        const PrismaClient = getGeneratedPrismaClient(target);
        const { prisma, close } = await factory();
        try {
          expect(typeof PrismaClient).toBe("function");
          expect(typeof prisma.$connect).toBe("function");
          expect(typeof prisma.$queryRawUnsafe).toBe("function");
          await expect(prisma.$queryRawUnsafe("SELECT 1")).resolves.toBeDefined();
        } finally {
          await close();
        }
      },
      LOCAL_TIMEOUT_MS,
    );

    it(
      "supports one-to-one and one-to-many reads against a real local database",
      async () => {
        const { orm, close } = await factory();
        try {
          await assertOneToOneAndHasManyQueries(orm, expect);
        } finally {
          await close();
        }
      },
      LOCAL_TIMEOUT_MS,
    );

    it(
      "supports belongsTo and many-to-many traversal against a real local database",
      async () => {
        const { orm, close } = await factory();
        try {
          await assertBelongsToAndManyToManyQueries(orm, expect);
        } finally {
          await close();
        }
      },
      LOCAL_TIMEOUT_MS,
    );

    it(
      "supports updates, upserts, deletes, and transaction rollback against a real local database",
      async () => {
        const { orm, close } = await factory();
        try {
          await assertMutationQueries(orm, expect, { expectTransactionRollback: true });
        } finally {
          await close();
        }
      },
      LOCAL_TIMEOUT_MS,
    );
  });
}
