import { mkdir } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createOrm } from "@farming-labs/orm";
import { createPrismaDriver } from "@farming-labs/orm-prisma";
import type { AuthOrm } from "../../auth-store";
import { authSchema } from "../../schema";
import type { DemoRuntimeHandle } from "../shared/types";

// Generated by `pnpm run prisma:prepare` before the demo/test run.
// @ts-ignore generated demo client
import { PrismaClient } from "../../../prisma/generated/client/index.js";

const dirname = path.dirname(fileURLToPath(import.meta.url));
const prismaDirectory = path.resolve(dirname, "../../../prisma");
const prismaDatabasePath = path.join(prismaDirectory, "dev.db");
const prismaDatabaseUrl = `file:${prismaDatabasePath}`;

async function resetPrismaDatabase(prisma: InstanceType<typeof PrismaClient>) {
  await prisma.account.deleteMany();
  await prisma.session.deleteMany();
  await prisma.profile.deleteMany();
  await prisma.user.deleteMany();
}

export async function createPrismaRuntime(): Promise<DemoRuntimeHandle> {
  await mkdir(prismaDirectory, { recursive: true });

  const prisma = new PrismaClient({
    datasources: {
      db: {
        url: prismaDatabaseUrl,
      },
    },
  });

  await prisma.$connect();
  await resetPrismaDatabase(prisma);

  const orm: AuthOrm = createOrm({
    schema: authSchema,
    driver: createPrismaDriver<typeof authSchema>({
      client: prisma as any,
    }),
  });

  return {
    name: "prisma",
    label: "Prisma runtime",
    client: "Generated PrismaClient",
    orm,
    directCheck: async (userId) =>
      prisma.user.findUnique({
        where: {
          id: userId,
        },
        select: {
          id: true,
          email: true,
        },
      }),
    close: async () => {
      await prisma.$disconnect();
    },
  };
}
