import { randomUUID } from "node:crypto";
import { mkdir, mkdtemp, rm } from "node:fs/promises";
import { tmpdir, userInfo } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { DatabaseSync } from "node:sqlite";
import mysql from "mysql2/promise";
import mongoose from "mongoose";
import { Client, Pool } from "pg";
import { createMongooseDriver, type MongooseModelLike } from "@farming-labs/orm-mongoose";
import { createPrismaDriver } from "@farming-labs/orm-prisma";
import {
  createMysqlDriver,
  createPgClientDriver,
  createPgPoolDriver,
  createSqliteDriver,
  type MysqlConnectionLike,
  type MysqlPoolLike,
} from "@farming-labs/orm-sql";
import { createMemoryDriver, createOrm, renderSafeSql } from "@farming-labs/orm";
import { createAuthStore, type AuthOrm } from "./auth-store";
import { authSchema } from "./schema";

// Generated by `pnpm run prisma:prepare` before the demo/test run.
// @ts-ignore generated demo client
import { PrismaClient } from "../prisma/generated/client/index.js";

const dirname = path.dirname(fileURLToPath(import.meta.url));
const prismaDirectory = path.resolve(dirname, "../prisma");
const prismaDatabasePath = path.join(prismaDirectory, "dev.db");
const prismaDatabaseUrl = `file:${prismaDatabasePath}`;

export type DemoAdapterName =
  | "memory"
  | "sqlite"
  | "prisma"
  | "postgres-pool"
  | "postgres-client"
  | "mysql-pool"
  | "mysql-connection"
  | "mongoose";

export type DemoAdapterInput = DemoAdapterName | "all";

type DirectCheckResult = {
  id: string;
  email: string;
} | null;

type AvailabilityResult = {
  available: boolean;
  reason?: string;
};

type DemoRuntimeHandle = {
  name: DemoAdapterName;
  label: string;
  client: string;
  orm: AuthOrm;
  directCheck?: (userId: string) => Promise<DirectCheckResult>;
  close: () => Promise<void>;
};

type DemoAdapterFactory = {
  label: string;
  client: string;
  availability: () => Promise<AvailabilityResult>;
  create: () => Promise<DemoRuntimeHandle>;
};

const pgDefaultAdminUrl = `postgres://${userInfo().username}@127.0.0.1:5432/postgres`;
const pgAdminUrl =
  process.env.FARM_ORM_DEMO_PG_ADMIN_URL ??
  process.env.FARM_ORM_LOCAL_PG_ADMIN_URL ??
  pgDefaultAdminUrl;
const mysqlAdminUrl =
  process.env.FARM_ORM_DEMO_MYSQL_ADMIN_URL ??
  process.env.FARM_ORM_LOCAL_MYSQL_ADMIN_URL ??
  "mysql://root@127.0.0.1:3306";
const mongoBaseUrl =
  process.env.FARM_ORM_DEMO_MONGODB_URL ??
  process.env.FARM_ORM_LOCAL_MONGODB_URL ??
  "mongodb://127.0.0.1:27017";

function createIsolatedName(prefix: string) {
  return `${prefix}_${randomUUID().replace(/-/g, "")}`;
}

function assignDatabase(connectionString: string, databaseName: string) {
  const url = new URL(connectionString);
  url.pathname = `/${databaseName}`;
  return url.toString();
}

function assignMongoDatabase(connectionString: string, databaseName: string) {
  const url = new URL(connectionString);
  url.pathname = `/${databaseName}`;
  return url.toString();
}

function formatLocalRuntimeError(label: string, error: unknown, hint: string) {
  const message = error instanceof Error ? error.message : String(error);
  return new Error(`${label} demo runtime could not connect. ${hint}\nOriginal error: ${message}`);
}

function toDirectCheck(
  row?: { id?: string | null; email?: string | null; email_address?: string | null } | null,
) {
  if (!row?.id) return null;
  return {
    id: row.id,
    email: row.email ?? row.email_address ?? "",
  };
}

async function applyStatements(
  execute: (statement: string) => Promise<unknown> | unknown,
  sql: string,
) {
  const statements = sql
    .split(";")
    .map((statement) => statement.trim())
    .filter(Boolean);

  for (const statement of statements) {
    await execute(`${statement};`);
  }
}

function asMysqlConnectionLike(connection: mysql.PoolConnection): MysqlConnectionLike {
  return {
    execute(sql, params) {
      return connection.execute(sql as string, params as any) as Promise<[any, unknown]>;
    },
    beginTransaction() {
      return connection.beginTransaction();
    },
    commit() {
      return connection.commit();
    },
    rollback() {
      return connection.rollback();
    },
    release() {
      connection.release();
    },
  };
}

function asMysqlPoolLike(pool: mysql.Pool): MysqlPoolLike {
  return {
    execute(sql, params) {
      return pool.execute(sql as string, params as any) as Promise<[any, unknown]>;
    },
    async getConnection() {
      return asMysqlConnectionLike(await pool.getConnection());
    },
  };
}

function asMongooseModelLike(model: mongoose.Model<any>) {
  return model as unknown as MongooseModelLike;
}

const memorySeed = () => ({
  user: [],
  profile: [],
  session: [],
  account: [],
});

async function resetPrismaDatabase(prisma: InstanceType<typeof PrismaClient>) {
  await prisma.account.deleteMany();
  await prisma.session.deleteMany();
  await prisma.profile.deleteMany();
  await prisma.user.deleteMany();
}

async function alwaysAvailable() {
  return {
    available: true,
  } satisfies AvailabilityResult;
}

async function probePostgres(): Promise<AvailabilityResult> {
  const pool = new Pool({ connectionString: pgAdminUrl });

  try {
    await pool.query("select 1");
    return {
      available: true,
    };
  } catch (error) {
    return {
      available: false,
      reason: formatLocalRuntimeError(
        "PostgreSQL",
        error,
        `Set FARM_ORM_DEMO_PG_ADMIN_URL or FARM_ORM_LOCAL_PG_ADMIN_URL if your local admin URL is not ${pgAdminUrl}.`,
      ).message,
    };
  } finally {
    await pool.end().catch(() => undefined);
  }
}

async function probeMysql(): Promise<AvailabilityResult> {
  const pool = mysql.createPool(mysqlAdminUrl);

  try {
    await pool.query("select 1");
    return {
      available: true,
    };
  } catch (error) {
    return {
      available: false,
      reason: formatLocalRuntimeError(
        "MySQL",
        error,
        `Set FARM_ORM_DEMO_MYSQL_ADMIN_URL or FARM_ORM_LOCAL_MYSQL_ADMIN_URL if your local admin URL is not ${mysqlAdminUrl}.`,
      ).message,
    };
  } finally {
    await pool.end().catch(() => undefined);
  }
}

async function probeMongo(): Promise<AvailabilityResult> {
  const connection = mongoose.createConnection(mongoBaseUrl, {
    serverSelectionTimeoutMS: 2_500,
    connectTimeoutMS: 2_500,
  });

  try {
    await connection.asPromise();
    return {
      available: true,
    };
  } catch (error) {
    return {
      available: false,
      reason: formatLocalRuntimeError(
        "MongoDB",
        error,
        `Set FARM_ORM_DEMO_MONGODB_URL or FARM_ORM_LOCAL_MONGODB_URL if your local MongoDB URL is not ${mongoBaseUrl}.`,
      ).message,
    };
  } finally {
    await connection.close().catch(() => undefined);
  }
}

async function createMemoryRuntime(): Promise<DemoRuntimeHandle> {
  const orm: AuthOrm = createOrm({
    schema: authSchema,
    driver: createMemoryDriver<typeof authSchema>(memorySeed()),
  });

  return {
    name: "memory",
    label: "Memory runtime",
    client: "Seeded in-memory store",
    orm,
    close: async () => {},
  };
}

async function createSqliteRuntime(): Promise<DemoRuntimeHandle> {
  const directory = await mkdtemp(path.join(tmpdir(), "farm-orm-demo-sqlite-"));
  const databasePath = path.join(directory, "demo.db");
  const database = new DatabaseSync(databasePath);

  await applyStatements(
    database.exec.bind(database),
    renderSafeSql(authSchema, { dialect: "sqlite" }),
  );

  const orm: AuthOrm = createOrm({
    schema: authSchema,
    driver: createSqliteDriver<typeof authSchema>(database),
  });

  return {
    name: "sqlite",
    label: "SQLite runtime",
    client: "node:sqlite DatabaseSync",
    orm,
    directCheck: async (userId) => {
      const rows = database
        .prepare('select "id", "email_address" from "users" where "id" = ?')
        .all(userId) as Array<{ id: string; email_address: string }>;

      return toDirectCheck(rows[0]);
    },
    close: async () => {
      database.close();
      await rm(directory, { recursive: true, force: true });
    },
  };
}

async function createPrismaRuntime(): Promise<DemoRuntimeHandle> {
  await mkdir(prismaDirectory, { recursive: true });

  const prisma = new PrismaClient({
    datasources: {
      db: {
        url: prismaDatabaseUrl,
      },
    },
  });

  await prisma.$connect();
  await resetPrismaDatabase(prisma);

  const orm: AuthOrm = createOrm({
    schema: authSchema,
    driver: createPrismaDriver<typeof authSchema>({
      client: prisma as any,
    }),
  });

  return {
    name: "prisma",
    label: "Prisma runtime",
    client: "Generated PrismaClient",
    orm,
    directCheck: async (userId) =>
      prisma.user.findUnique({
        where: {
          id: userId,
        },
        select: {
          id: true,
          email: true,
        },
      }),
    close: async () => {
      await prisma.$disconnect();
    },
  };
}

async function createPostgresPoolRuntime(): Promise<DemoRuntimeHandle> {
  const databaseName = createIsolatedName("farm_orm_demo_pg_pool");
  const adminPool = new Pool({ connectionString: pgAdminUrl });

  try {
    await adminPool.query(`create database "${databaseName}"`);
  } catch (error) {
    await adminPool.end();
    throw formatLocalRuntimeError(
      "PostgreSQL",
      error,
      `Set FARM_ORM_DEMO_PG_ADMIN_URL or FARM_ORM_LOCAL_PG_ADMIN_URL if your local admin URL is not ${pgAdminUrl}.`,
    );
  }

  await adminPool.end();

  const databaseUrl = assignDatabase(pgAdminUrl, databaseName);
  const pool = new Pool({ connectionString: databaseUrl });

  try {
    await applyStatements(
      (statement) => pool.query(statement),
      renderSafeSql(authSchema, { dialect: "postgres" }),
    );
  } catch (error) {
    await pool.end();
    const cleanupAdmin = new Pool({ connectionString: pgAdminUrl });
    await cleanupAdmin.query(`drop database if exists "${databaseName}"`);
    await cleanupAdmin.end();
    throw error;
  }

  const orm: AuthOrm = createOrm({
    schema: authSchema,
    driver: createPgPoolDriver<typeof authSchema>(pool),
  });

  return {
    name: "postgres-pool",
    label: "PostgreSQL runtime (pool)",
    client: "pg Pool",
    orm,
    directCheck: async (userId) => {
      const result = await pool.query('select "id", "email_address" from "users" where "id" = $1', [
        userId,
      ]);
      return toDirectCheck(result.rows[0] as { id: string; email_address: string } | undefined);
    },
    close: async () => {
      await pool.end();
      const cleanupAdmin = new Pool({ connectionString: pgAdminUrl });
      await cleanupAdmin.query(
        "select pg_terminate_backend(pid) from pg_stat_activity where datname = $1 and pid <> pg_backend_pid()",
        [databaseName],
      );
      await cleanupAdmin.query(`drop database if exists "${databaseName}"`);
      await cleanupAdmin.end();
    },
  };
}

async function createPostgresClientRuntime(): Promise<DemoRuntimeHandle> {
  const databaseName = createIsolatedName("farm_orm_demo_pg_client");
  const adminPool = new Pool({ connectionString: pgAdminUrl });

  try {
    await adminPool.query(`create database "${databaseName}"`);
  } catch (error) {
    await adminPool.end();
    throw formatLocalRuntimeError(
      "PostgreSQL",
      error,
      `Set FARM_ORM_DEMO_PG_ADMIN_URL or FARM_ORM_LOCAL_PG_ADMIN_URL if your local admin URL is not ${pgAdminUrl}.`,
    );
  }

  await adminPool.end();

  const databaseUrl = assignDatabase(pgAdminUrl, databaseName);
  const client = new Client({ connectionString: databaseUrl });
  await client.connect();

  try {
    await applyStatements(
      (statement) => client.query(statement),
      renderSafeSql(authSchema, { dialect: "postgres" }),
    );
  } catch (error) {
    await client.end().catch(() => undefined);
    const cleanupAdmin = new Pool({ connectionString: pgAdminUrl });
    await cleanupAdmin.query(`drop database if exists "${databaseName}"`);
    await cleanupAdmin.end();
    throw error;
  }

  const orm: AuthOrm = createOrm({
    schema: authSchema,
    driver: createPgClientDriver<typeof authSchema>(client),
  });

  return {
    name: "postgres-client",
    label: "PostgreSQL runtime (client)",
    client: "pg Client",
    orm,
    directCheck: async (userId) => {
      const result = await client.query(
        'select "id", "email_address" from "users" where "id" = $1',
        [userId],
      );
      return toDirectCheck(result.rows[0] as { id: string; email_address: string } | undefined);
    },
    close: async () => {
      await client.end();
      const cleanupAdmin = new Pool({ connectionString: pgAdminUrl });
      await cleanupAdmin.query(
        "select pg_terminate_backend(pid) from pg_stat_activity where datname = $1 and pid <> pg_backend_pid()",
        [databaseName],
      );
      await cleanupAdmin.query(`drop database if exists "${databaseName}"`);
      await cleanupAdmin.end();
    },
  };
}

async function createMysqlPoolRuntime(): Promise<DemoRuntimeHandle> {
  const databaseName = createIsolatedName("farm_orm_demo_mysql_pool");
  const adminPool = mysql.createPool(mysqlAdminUrl);

  try {
    await adminPool.query(`create database \`${databaseName}\``);
  } catch (error) {
    await adminPool.end();
    throw formatLocalRuntimeError(
      "MySQL",
      error,
      `Set FARM_ORM_DEMO_MYSQL_ADMIN_URL or FARM_ORM_LOCAL_MYSQL_ADMIN_URL if your local admin URL is not ${mysqlAdminUrl}.`,
    );
  }

  await adminPool.end();

  const databaseUrl = assignDatabase(mysqlAdminUrl, databaseName);
  const pool = mysql.createPool(databaseUrl);

  try {
    await applyStatements(
      (statement) => pool.query(statement),
      renderSafeSql(authSchema, { dialect: "mysql" }),
    );
  } catch (error) {
    await pool.end();
    const cleanupAdmin = mysql.createPool(mysqlAdminUrl);
    await cleanupAdmin.query(`drop database if exists \`${databaseName}\``);
    await cleanupAdmin.end();
    throw error;
  }

  const orm: AuthOrm = createOrm({
    schema: authSchema,
    driver: createMysqlDriver<typeof authSchema>(asMysqlPoolLike(pool)),
  });

  return {
    name: "mysql-pool",
    label: "MySQL runtime (pool)",
    client: "mysql2 pool",
    orm,
    directCheck: async (userId) => {
      const [rows] = await pool.query("select `id`, `email_address` from `users` where `id` = ?", [
        userId,
      ]);
      return toDirectCheck((rows as Array<{ id: string; email_address: string }>)[0]);
    },
    close: async () => {
      await pool.end();
      const cleanupAdmin = mysql.createPool(mysqlAdminUrl);
      await cleanupAdmin.query(`drop database if exists \`${databaseName}\``);
      await cleanupAdmin.end();
    },
  };
}

async function createMysqlConnectionRuntime(): Promise<DemoRuntimeHandle> {
  const databaseName = createIsolatedName("farm_orm_demo_mysql_conn");
  const adminPool = mysql.createPool(mysqlAdminUrl);

  try {
    await adminPool.query(`create database \`${databaseName}\``);
  } catch (error) {
    await adminPool.end();
    throw formatLocalRuntimeError(
      "MySQL",
      error,
      `Set FARM_ORM_DEMO_MYSQL_ADMIN_URL or FARM_ORM_LOCAL_MYSQL_ADMIN_URL if your local admin URL is not ${mysqlAdminUrl}.`,
    );
  }

  await adminPool.end();

  const databaseUrl = assignDatabase(mysqlAdminUrl, databaseName);
  const pool = mysql.createPool(databaseUrl);
  const connection = await pool.getConnection();

  try {
    await applyStatements(
      (statement) => connection.query(statement),
      renderSafeSql(authSchema, { dialect: "mysql" }),
    );
  } catch (error) {
    connection.release();
    await pool.end();
    const cleanupAdmin = mysql.createPool(mysqlAdminUrl);
    await cleanupAdmin.query(`drop database if exists \`${databaseName}\``);
    await cleanupAdmin.end();
    throw error;
  }

  const orm: AuthOrm = createOrm({
    schema: authSchema,
    driver: createMysqlDriver<typeof authSchema>(asMysqlConnectionLike(connection)),
  });

  return {
    name: "mysql-connection",
    label: "MySQL runtime (connection)",
    client: "mysql2 connection",
    orm,
    directCheck: async (userId) => {
      const [rows] = await connection.query(
        "select `id`, `email_address` from `users` where `id` = ?",
        [userId],
      );
      return toDirectCheck((rows as Array<{ id: string; email_address: string }>)[0]);
    },
    close: async () => {
      connection.release();
      await pool.end();
      const cleanupAdmin = mysql.createPool(mysqlAdminUrl);
      await cleanupAdmin.query(`drop database if exists \`${databaseName}\``);
      await cleanupAdmin.end();
    },
  };
}

async function createMongooseRuntime(): Promise<DemoRuntimeHandle> {
  const databaseUrl = assignMongoDatabase(mongoBaseUrl, createIsolatedName("farm_orm_demo_mongo"));
  const connection = mongoose.createConnection(databaseUrl, {
    serverSelectionTimeoutMS: 2_500,
    connectTimeoutMS: 2_500,
  });

  try {
    await connection.asPromise();
  } catch (error) {
    await connection.close().catch(() => undefined);
    throw formatLocalRuntimeError(
      "MongoDB",
      error,
      `Set FARM_ORM_DEMO_MONGODB_URL or FARM_ORM_LOCAL_MONGODB_URL if your local MongoDB URL is not ${mongoBaseUrl}.`,
    );
  }

  const userSchema = new mongoose.Schema(
    {
      id: { type: String, required: true, unique: true },
      name: { type: String, required: true },
      email_address: { type: String, required: true, unique: true },
      emailVerified: { type: Boolean, default: false },
      createdAt: { type: Date, default: Date.now },
      updatedAt: { type: Date, default: Date.now },
    },
    { versionKey: false },
  );

  const profileSchema = new mongoose.Schema(
    {
      id: { type: String, required: true, unique: true },
      userId: { type: String, required: true, unique: true },
      bio: { type: String, default: null },
    },
    { versionKey: false },
  );

  const sessionSchema = new mongoose.Schema(
    {
      id: { type: String, required: true, unique: true },
      userId: { type: String, required: true },
      token: { type: String, required: true, unique: true },
      expiresAt: { type: Date, required: true },
    },
    { versionKey: false },
  );

  const accountSchema = new mongoose.Schema(
    {
      id: { type: String, required: true, unique: true },
      userId: { type: String, required: true },
      provider: { type: String, required: true },
      accountId: { type: String, required: true },
    },
    { versionKey: false },
  );

  const UserModel = connection.model("DemoUser", userSchema, "users");
  const ProfileModel = connection.model("DemoProfile", profileSchema, "profiles");
  const SessionModel = connection.model("DemoSession", sessionSchema, "sessions");
  const AccountModel = connection.model("DemoAccount", accountSchema, "accounts");

  const orm: AuthOrm = createOrm({
    schema: authSchema,
    driver: createMongooseDriver<typeof authSchema>({
      models: {
        user: asMongooseModelLike(UserModel),
        profile: asMongooseModelLike(ProfileModel),
        session: asMongooseModelLike(SessionModel),
        account: asMongooseModelLike(AccountModel),
      },
    }),
  });

  return {
    name: "mongoose",
    label: "MongoDB runtime",
    client: "Mongoose models",
    orm,
    directCheck: async (userId) => {
      const row = await UserModel.findOne({
        id: userId,
      })
        .lean()
        .exec();

      return toDirectCheck(row as { id?: string; email_address?: string } | null | undefined);
    },
    close: async () => {
      await connection.dropDatabase();
      await connection.close();
    },
  };
}

export const demoAdapters: Record<DemoAdapterName, DemoAdapterFactory> = {
  memory: {
    label: "Memory runtime",
    client: "Seeded in-memory store",
    availability: alwaysAvailable,
    create: createMemoryRuntime,
  },
  sqlite: {
    label: "SQLite runtime",
    client: "node:sqlite DatabaseSync",
    availability: alwaysAvailable,
    create: createSqliteRuntime,
  },
  prisma: {
    label: "Prisma runtime",
    client: "Generated PrismaClient",
    availability: alwaysAvailable,
    create: createPrismaRuntime,
  },
  "postgres-pool": {
    label: "PostgreSQL runtime (pool)",
    client: "pg Pool",
    availability: probePostgres,
    create: createPostgresPoolRuntime,
  },
  "postgres-client": {
    label: "PostgreSQL runtime (client)",
    client: "pg Client",
    availability: probePostgres,
    create: createPostgresClientRuntime,
  },
  "mysql-pool": {
    label: "MySQL runtime (pool)",
    client: "mysql2 pool",
    availability: probeMysql,
    create: createMysqlPoolRuntime,
  },
  "mysql-connection": {
    label: "MySQL runtime (connection)",
    client: "mysql2 connection",
    availability: probeMysql,
    create: createMysqlConnectionRuntime,
  },
  mongoose: {
    label: "MongoDB runtime",
    client: "Mongoose models",
    availability: probeMongo,
    create: createMongooseRuntime,
  },
};

export const selfContainedDemoAdapters = [
  "memory",
  "sqlite",
  "prisma",
] as const satisfies readonly DemoAdapterName[];
export const localDemoAdapters = [
  "postgres-pool",
  "postgres-client",
  "mysql-pool",
  "mysql-connection",
  "mongoose",
] as const satisfies readonly DemoAdapterName[];
export const allDemoAdapters = Object.keys(demoAdapters) as DemoAdapterName[];
export const defaultDemoAdapter: DemoAdapterName = "memory";

export async function probeDemoAdapter(adapterName: DemoAdapterName) {
  return demoAdapters[adapterName].availability();
}

export function parseDemoAdapterName(input?: string): DemoAdapterInput {
  if (!input) return defaultDemoAdapter;
  if (input === "all") return "all";
  if (Object.hasOwn(demoAdapters, input)) return input as DemoAdapterName;

  throw new Error(
    `Unknown demo adapter "${input}". Expected one of: ${[...allDemoAdapters, "all"].join(", ")}.`,
  );
}

export async function runUnifiedAuthDemo(adapterName: DemoAdapterName = defaultDemoAdapter) {
  const runtime = await demoAdapters[adapterName].create();

  try {
    const auth = createAuthStore(runtime.orm);

    const created = await auth.createOAuthUser({
      name: "Ada Lovelace",
      email: "ada@farminglabs.dev",
      provider: "github",
      accountId: "gh_ada",
    });

    await runtime.orm.profile.create({
      data: {
        userId: created.user.id,
        bio: `Unified auth flow running through ${runtime.client}.`,
      },
    });

    const rotated = await auth.rotateSession({
      userId: created.user.id,
      token: "session-token",
      expiresAt: new Date("2027-01-01T00:00:00.000Z"),
    });

    const user = await auth.findUserByEmail("ADA@FARMINGLABS.DEV");
    const summary = await auth.getAuthSummary(created.user.id);
    const directCheck = runtime.directCheck ? await runtime.directCheck(created.user.id) : null;

    return {
      adapter: {
        name: runtime.name,
        label: runtime.label,
        client: runtime.client,
      },
      created,
      rotated,
      user,
      summary,
      directCheck,
    };
  } finally {
    await runtime.close();
  }
}

export async function runAvailableUnifiedAuthDemos() {
  const executed: Array<Awaited<ReturnType<typeof runUnifiedAuthDemo>>> = [];
  const skipped: Array<{ name: DemoAdapterName; reason: string }> = [];

  for (const adapterName of allDemoAdapters) {
    const availability = await probeDemoAdapter(adapterName);
    if (!availability.available) {
      skipped.push({
        name: adapterName,
        reason: availability.reason ?? "Unavailable on this machine.",
      });
      continue;
    }

    executed.push(await runUnifiedAuthDemo(adapterName));
  }

  return {
    executed,
    skipped,
  };
}

export type UnifiedDemoResult = Awaited<ReturnType<typeof runUnifiedAuthDemo>>;
